S9/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # includem url-urile din app polls, cu prefixul /polls
    path("polls/", include("polls.urls"), name='polls'),
    path('admin/', admin.site.urls),
]

S9/mysite/polls/urls.py
"""
Fisier local de urls, fiecare app o sa aiba cate unul.
Dupa ce definim aici endpoints, le importam in fisierul global,
care este mysite/urls.py.

"""
from django.urls import path

from . import views

"""
Intotdeauna vom avea o lista de tipul urlpatterns,
in care vom apela functia 
path("<url relativ>", <view>, <nume view>)
"""
# aceasta variabila ne permite sa ne referim la URL-urile de mai jos cu prefixul polls,
# de exemplu "polls:hello"
app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("hello/<str:name>", views.hello, name="hello"),
    path("<int:question_id>", views.detail, name="detail"),
    path("<int:question_id>/results", views.results, name="results"),
    path("<int:question_id>/vote", views.vote, name="vote")
]

S9/mysite/polls/models.py
from django.db import models

# Create your models here.

from django.db import models

"""
Fiecare model va fi o clasa care extinde (mostenire) clasa models.Model,
si care contine atributele pe care dorim sa le punem noi in tabela modelului nostru.

Un atribut reprezinta o coloana din tabela SQL, si se numeste Field.
Definim aceste fields folosind clase existente in Django, precum:
- CharField -> va face in SQL un VARCHAR
- DateTimeField -> va face un DATETIME
- IntegerField
- BooleanField

Pentru relatii, este la fel de simplu, adaugam din nou niste atribute, doar ca pe acestea le legam de alte modele:
- ForeignKey -> defineste o relatie de genul 1-to-many, adica o intrebare (Question) are mai multe optiuni de raspuns (Choice)
- OneToOneField -> defineste o relatie de genul 1-to-1
- ManyToManyField -> defineste o relatie de genul many-to-many, de exemplu Product si Order (un produs se poate regasi
    in mai multe comenzi, iar o comanda poate avea mai multe produse).
"""


class Question(models.Model):
    question_text = models.CharField(max_length=200)    # VARCHAR cu limita de 200 caractere
    pub_date = models.DateTimeField("date published")   # DATETIME cu data publicarii

    def __str__(self):
        # str este reprezentarea sub forma de string a unui obiect
        return self.question_text


class Choice(models.Model):
    # FK catre Question, deoarece un Choice poate sa fie doar pentru un Question
    # on_delete = stabileste comportamentul acestui model atunci cand noi stergem modelul referentiat
    # CASCADE = stergem si modelul curent (adica daca se sterge intrebarea, stergem si toate variantele de raspuns)
    # Relatia inversa ( de la question la choice) va fi denumita choice_set (adica numele modelului curent + '_set')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    # VARCHAR cu limita de 200, aici avem textul raspunsului
    choice_text = models.CharField(max_length=200)
    # numarul de voturi, INT, default 0 ca sa il putem incrementa
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

S9/mysite/polls/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse

from .models import Question, Choice


def index_old(request):
    # Question.objects = object manager care ne ajuta sa interogam baza de date
    # order_by("-pub_date") = se va transforma in ORDER BY pub_date DESC
    # (faptul ca avem minus in fata lui pub_date il face desc)
    # [:5] = list slicing, va scoate doar primele 5 rezultate, iar in SQL asta se traduce prin LIMIT 5
    # Deci latest_question_list va contine ultimele 5 poll-uri adaugate in DB
    latest_question_list = Question.objects.order_by("-pub_date")[:3]
    # [q.question_text for q in latest_question_list]
    # Conceptul de mai sus se numeste list comprehension (compresie de lista) si este o forma mai scurta de a scrie:
    """
    l = []
    for q in latest_question_list:
        l.append(q.question_text)
    """
    # Astfel, in acesta lista vom avea stringurile care reprezinta textul fiecarei intrebari din cele 5 luate din db
    # "\n ".join(list) uneste toate elementele din lista, folosind "\n " intre ele
    # "\n " = caracterul newline
    output = "\n ".join([q.question_text for q in latest_question_list])
    # aici returnam raspunsul, care by default o sa aiba status code 200 (SUCCESS)
    return HttpResponse(output)

def index_long(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    # Incarcam template-ul facut de noi, folosind path-ul acestuia
    template = loader.get_template("polls/index.html")
    # Contextul ne ajuta sa trimitem informatii din view catre template
    # acesta este de fapt doar un dictionar, in care cheia este numele pe care il vom folosi in template
    # iar valoarea este ceea ce vrem noi sa trimite (de obicei o variabila)
    context = {
        "latest_question_list": latest_question_list,
    }
    # returnam un HTTP response (200) care randeaza template-ul index.html folosind contextul de mai sus
    # template.render(context, request) => aceasta este partea care transforma template-ul intr-un fisier HTML pur
    return HttpResponse(template.render(context, request))

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {
        "latest_question_list": latest_question_list,
    }

    # Shortcut pentru randarea unui template:
    # render(request, <nume template>, context)
    return render(request, "polls/index.html", context)

"""
Pentru views in care avem parametrii dinamici (ex. id unei intrebari),
acest parametru va fi injectat din URL direct ca si argument in functia noastra de view

In URL trebuie sa avem o structura de tipul <tip param:nume param>, exemplu:
<str:name> 
"""
def hello(request, name):
    return HttpResponse(f"Hello, {name}, how are you?")


def detail_with_try_except(request, question_id):
    # Aici vrem sa vedem detaliile unei intrebari, deci prima data trebuie sa o luam din baza de date
    try:
        q = Question.objects.get(id=question_id)
    except Question.DoesNotExist:
        # Tratam cazul in care intrebarea cu ID-ul cerut nu exista
        raise Http404("Question does not exist")
    # Apoi trebuie sa ii pasam template-ului nostru obiectul de question
    context = {
        'q': q
    }
    # In final, randam template-ul si il returnam ca si raspuns
    return render(request, "polls/detail.html", context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


"""
In tutorial, aici mai erau niste pasi de exception handling, dar au fost omisi pentru simplicitate.
"""
def vote(request, question_id):
    # Pentru a putea vota, prima data preluam intrebarea pe care s-a votat
    question = get_object_or_404(Question, pk=question_id)
    # Apoi luam din form optiunea selectata
    selected_choice_id = request.POST['choice']
    # Acum trebuie sa luam optiunea selectata ca si obiect din baza de date
    selected_choice = get_object_or_404(Choice, pk=selected_choice_id)
    # Incrementam numarul de voturi pentru optiunea selectata
    selected_choice.votes += 1
    # IMPORTANT: salvam modificarile in baza de date!!
    selected_choice.save()
    # Calculam url-ul de redirectionare (catre pagina de rezultate)
    redirect_url = reverse("polls:results", args=(question.id,))
    # Redirectam utilizatorul catre pagina de results dupa votarea cu succes
    return HttpResponseRedirect(redirect_url)

S9/mysite/polls/templates/polls/detail.html
{# h1 - cel mai mare header, sunt de la h1 pana la h6 #}
<h1>{{ question.question_text }}</h1>
<ul>
    {# iteram prin toate optiunile de raspuns, si le afisam intr-o lista neordonata #}
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
    {% endfor %}
</ul>

<h2> De aici incolo avem partea de VOTARE </h2>

{# form = formular care face un POST catre URL-ul definit in action #}
{# pentru URL, avem nevoie de numele pe care l-am pus in path #}
<form action="{% url 'polls:vote' question.id %}" method="post">
{# CSRF token = este un tag obligatoriu pentru metodele POST, acesta este un token invizibil generat automat de Django pentru a preveni atacurile cibernetice #}
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>

    {# pentru fiecare optiune de raspuns, afisam un buton radio, si  numele optiunii #}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    {# line break, pune practic o linie goala intre optiuni #}
    <br>
    {% endfor %}
</fieldset>
    {# butonul de submit #}
<input type="submit" value="Vote">
</form>

S9/mysite/polls/templates/polls/index.html
{# asa punem comentarii in template-urile Django #}

{% if latest_question_list %}
    <ul>  {# ul este unordered list #}
    {% for question in latest_question_list %}
        {# li = list item, a = link #}
        <li>
            {# /polls/{{ question.id }} se va evalua ca /polls/1 , /polls/2 , etc. #}
            <a href="/polls/{{ question.id }}">{{ question.question_text }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

S9/mysite/polls/templates/polls/results.html
<h1> Rezultate votare: </h1>
<h2> {{ question.question_text }} </h2>

<ul>
{% for choice in question.choice_set.all %}
  <li>
    {{ choice.choice_text }} : {{ choice.votes }} voturi
  </li>
{% endfor %}
</ul>